services:
  # Database service
  postgres:
    container_name: postgres_dev
    image: postgres:17.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_app_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app_network_dev
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  # Database management UI
  pgadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app_network_dev
    depends_on:
      - postgres

  # Backend API service
  api:
    container_name: api_dev
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    restart: unless-stopped
    ports:
      - '3001:3001'
      - '9229:9229'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres_dev:5432/finance_app_dev
      - PORT=3001
      - DEBUG=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true # Add this for better file watching
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/packages/eslint-config/node_modules
      - /app/packages/typescript-config/node_modules
    command: nodemon --watch apps/api/src -e ts,js --exec pnpm dev --filter api # Override CMD from Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network_dev

  # Frontend web application
  web:
    container_name: web_dev
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001 # Public API URL for browser requests
      - API_URL=http://api_dev:3001 # Internal API URL for server-side requests
      - NEXT_WEBPACK_USEPOLLING=1 # Enable webpack polling for hot reload
    volumes:
      - .:/app # Mount entire project
      - /app/node_modules # Exclude root node_modules
      - /app/apps/web/node_modules # Exclude web node_modules
      - /app/apps/web/.next # Exclude Next.js build
      - /app/packages/eslint-config/node_modules # Exclude shared package node_modules
      - /app/packages/typescript-config/node_modules
    command: pnpm dev --filter web
    depends_on:
      - api
    networks:
      - app_network_dev

# Persistent storage for PostgreSQL data
volumes:
  postgres_dev_data:
    name: finance_app_postgres_dev_data

# Network configuration for service communication
networks:
  app_network_dev:
    driver: bridge
    name: finance_app_dev_network
