module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testEnvironment: 'node',
  testRegex: '.e2e-spec.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!**/**/index.ts',
    '!**/config/**',
    '!config/**',
    '!src/**/*.test.ts',
    '!src/**/*.spec.ts',
    '!e2e/**',
    '!**/**/__tests__/**',
    '!src/**/__tests__/**',
    '!**/**/tests/**',
    '!**/**/*.fixtures.ts',
    '!**/**/*.fixture.ts',
    '!**/**/*.dto.ts',
    '!**/**/main.ts',
    '!src/database/__tests__/**',
  ],
  coverageDirectory: '../coverage',
  coverageReporters: ['json', 'lcov', 'text', 'html'],
  forceCoverageMatch: ['**/*.ts'],
};
