module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testEnvironment: 'node',
  testRegex: '.e2e-spec.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/config/**/*.ts',
    '!**/*.config.ts',
    '!**/index.ts',
    '!**/*.{spec,test,e2e-spec}.ts',
    '!**/__tests__/**',
    '!**/test/**',
    '!**/*.{fixture,fixtures,dto,mock}.ts',
    '!**/main.ts',
    '!**/constants.ts',
    '!**/interfaces/**',
    '!**/types/**',
    '!**/enums/**',
  ],
  coverageDirectory: '../coverage',
  coverageReporters: ['json', 'lcov', 'text', 'html'],
  forceCoverageMatch: ['**/*.ts'],
};
