# GitHub Actions workflow for End-to-End testing
name: E2E Tests

# Trigger workflow on push to main/develop branches and PR events
on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize]

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Set up PostgreSQL service container for E2E tests
    services:
      postgres:
        image: postgres:17.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: finance_app_test
        ports:
          - 5432:5432
        # Health check ensures PostgreSQL is ready before tests run
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Environment variables available to all steps in this job
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/finance_app_test
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_API_URL: http://localhost:3001
      PLAYWRIGHT_BASE_URL: http://localhost:3000
      PLAYWRIGHT_API_URL: http://localhost:3001

    steps:
      # Check out repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up pnpm package manager
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.2.0

      # Setup Node.js environment with pnpm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install project dependencies
      - name: Install dependencies
        run: pnpm install

      # Build all packages in the monorepo
      - name: Build
        run: pnpm build

      # Install Playwright and its dependencies
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      # Execute end-to-end tests using Playwright
      - name: Run E2E Tests
        run: pnpm test:e2e

      # Upload test artifacts if tests fail for debugging
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
